
modLoader="javafml" #mandatory
loaderVersion="[40,)"
license="MIT License"
issueTrackerURL="https://github.com/eerussianguy/Better-Foliage/issues" #optional
[[mods]] #mandatory
modId="betterfoliage" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Better Foliage" #mandatory
displayURL="https://github.com/eerussianguy/Better-Foliage" #optional
logoFile="examplemod.png" #optional
credits="Paint_Ninja for the commission" #optional
authors="EERussianguy, PaintNinja" #optional
description='''
A slim port of Better Foliage for 1.16 and beyond.

Most changes are configurable via resource pack.
'''
[[dependencies.betterfoliage]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.betterfoliage]]
    modId="biomesoplenty"
    mandatory=false
    versionRange="[0,)"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.betterfoliage]]
    modId="quark"
    mandatory=false
    versionRange="[0,)"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.betterfoliage]]
    modId="atmospheric"
    mandatory=false
    versionRange="[0,)"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.betterfoliage]]
    modId="tfc"
    mandatory=false
    versionRange="[0,)"
    ordering="BEFORE"
    side="BOTH"
